tasks:
  - name: setup
    before: |
      echo "Setting up, please wait!"
      cd /workspace/bootcamp-fullstack-apps-with-cassandra 
      sed -i '1,$s/sdkman_auto_answer=false/sdkman_auto_answer=true/' /home/gitpod/.sdkman/etc/config 
      sed -i '1,$s/sdkman_selfupdate_enable=true/sdkman_selfupdate_enable=false/' /home/gitpod/.sdkman/etc/config 
      sdk install java 21.2.0.r11-grl -y
      pip3 install cassandra-driver
      npm install cassandra-driver
ports: 
  - port: 5005
  - port: 8080
  - port: 8081
    onOpen: open-browser 

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
